version: '3.8'

services:
  mongo-db:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-vehicular
    volumes:
      - ./mongo_data:/data/db
