export const EnvConfiguration = () => ({
  environment: process.env.NODE_ENV || 'dev',
  mongodb: process.env.MONGODB,
  port: process.env.PORT || 3000,
  cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinary_api_key: process.env.CLOUDINARY_API_KEY,
  cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET,
  jwt_secret: process.env.JWT_SECRET,
  jwt_expires_in: process.env.JWT_EXPIRES_IN,
  email_host: process.env.EMAIL_HOST,
  email_port: process.env.EMAIL_PORT,
  email_user: process.env.EMAIL_USER,
  email_pass: process.env.EMAIL_PASS,
  email_from: process.env.EMAIL_FROM,
  rest_api_url: process.env.REST_API_URL,
  google_client_id: process.env.GOOGLE_CLIENT_ID,
  google_client_secret: process.env.GOOGLE_CLIENT_SECRET,
  google_redirect_url: process.env.GOOGLE_REDIRECT_URL,
  front_url_redirect_login: process.env.FRONT_URL_REDIRECT_LOGIN,
  stripe_secret_key: process.env.STRIPE_SECRET_KEY,
  stripe_webhook_secret: process.env.STRIPE_WEBHOOK_SECRET,
  stripe_success_url: process.env.STRIPE_SUCCESS_URL,
  stripe_cancel_url: process.env.STRIPE_CANCEL_URL,
});

export enum EnvironmentConstants {
  environment = 'environment',
  mongodb = 'mongodb',
  port = 'port',
  cloudinary_cloud_name = 'cloudinary_cloud_name',
  cloudinary_api_key = 'cloudinary_api_key',
  cloudinary_api_secret = 'cloudinary_api_secret',
  jwt_secret = 'jwt_secret',
  jwt_expires_in = 'jwt_expires_in',
  email_host = 'email_host',
  email_port = 'email_port',
  email_user = 'email_user',
  email_pass = 'email_pass',
  email_from = 'email_from',
  rest_api_url = 'rest_api_url',
  google_client_id = 'google_client_id',
  google_client_secret = 'google_client_secret',
  google_redirect_url = 'google_redirect_url',
  front_url_redirect_login = 'front_url_redirect_login',
  stripe_secret_key = 'stripe_secret_key',
  stripe_webhook_secret = 'stripe_webhook_secret',
}
